name: Build Android APK

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: 20.5.1
            - uses: actions/setup-java@v3
              with:
                distribution: 'zulu' # See 'Supported distributions' for available options
                java-version: '17'
                cache: 'gradle'
            - name: Build Android application
              run: |
                npm install
                npm run build
                npm run android
                cd android
                ./gradlew assemble
              working-directory: ./e-pharmacy-frontend

            # upload debug
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "DebugAPK"
                files: e-pharmacy-frontend/android/app/build/outputs/apk/debug/app-debug.apk

                