name: Test Backend

on:
    push:
        branches: [main,back]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: 20.5.1
            - name: Setup up JDK 11
              uses: actions/setup-java@v2
              with:
                    java-version: '11'
                    distribution: 'adopt'
            - name: Build with Maven
              run: mvnw clean install -DskipTests
              working-directory: ./e-pharmacy-backend

            - name: Run tests
              run: mvnw test
              working-directory: ./e-pharmacy-backend

            