name: Test Frontend

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: 
                node-version: 20.5.1
            - name: Setup
              run: npm install
              working-directory: ./e-pharmacy-frontend

            - name: Run tests
              run: npm run test
              working-directory: ./e-pharmacy-frontend

            - name: Test if it builds
              run: npm run build
              working-directory: ./e-pharmacy-frontend
            