name: Test Backend

on:
    push:
        branches: [main,back]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
             
            - name: Setup up JDK 17
              uses: actions/setup-java@v2
              with:
                    java-version: '17'
                    distribution: 'adopt'
            - name: Build with Maven
              run: mvn -f pom.xml clean test
              working-directory: ./e-pharmacy-backend

           

            
